name: Deploy to DEV

on:
  workflow_dispatch:

jobs:
  vmstart:
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed
      - name: execute py script # run main.py
        run: python cron.py




# name: poc-workflow

# on:
#   workflow_dispatch:
#   push:
#     branches:
#       - 'WHFI-376-establish-cron-job'
# jobs:
#   vmstart:
#     runs-on: ubuntu
#     steps:
#       - name: actions/checkout
#       - uses: actions/checkout@v2

#       - name: setup python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.10' # install the python version needed

#       - name: execute py script # run main.py
#         run: python cron.py
